name: RNAseq
channels:
  - bioconda
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _libavif_api=1.1.1=h57928b3_2
  - _openmp_mutex=4.5=2_gnu
  - anndata=0.11.1=pyhd8ed1ab_1
  - anyio=4.8.0=pyhd8ed1ab_0
  - aom=3.9.1=he0c23c2_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py311he736701_5
  - array-api-compat=1.10.0=pyhd8ed1ab_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.4=pyhd8ed1ab_1
  - attrs=25.1.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.3=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blosc=1.21.6=hfd34d9b_1
  - brotli=1.1.0=h2466b09_2
  - brotli-bin=1.1.0=h2466b09_2
  - brotli-python=1.1.0=py311hda3d55a_2
  - bzip2=1.0.8=h2466b09_7
  - c-blosc2=2.15.2=h9e57077_1
  - ca-certificates=2025.1.31=h56e8100_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.2=h5782bbf_1
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py311he736701_0
  - charls=2.4.2=h1537add_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - click=8.1.8=pyh7428d3b_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.1=py311h3257749_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cython=3.0.12=py311h34f20a9_0
  - cytoolz=1.0.1=py311he736701_0
  - dask-core=2025.2.0=pyhd8ed1ab_0
  - dav1d=1.2.1=hcfcfb64_0
  - debugpy=1.8.12=py311hda3d55a_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=he0c23c2_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - fbpca=1.0=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.56.0=py311h5082efb_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.12.1=hdaf720e_2
  - fsspec=2025.2.0=pyhd8ed1ab_0
  - geosketch=1.3=pyhdfd78af_0
  - giflib=5.2.2=h64bf75a_0
  - glib=2.82.2=h3d4babf_1
  - glib-tools=2.82.2=h4394cf3_1
  - graphite2=1.3.13=h63175ca_1003
  - gst-plugins-base=1.24.7=hb0a98b8_0
  - gstreamer=1.24.7=h5006eae_0
  - h11=0.14.0=pyhd8ed1ab_1
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.12.1=nompi_py311haea1c80_103
  - harfbuzz=10.2.0=h885c0d4_0
  - harmonypy=0.0.10=pyhdfd78af_0
  - hdf5=1.14.4=nompi_hd5d9e70_105
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.10=pyhd8ed1ab_1
  - imagecodecs=2024.12.30=py311he589a3b_0
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_metadata=8.6.1=hd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2024.2.1=h57928b3_1083
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.32.0=pyh9ab4c32_0
  - ipywidgets=8.1.5=pyhd8ed1ab_1
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.5=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - json5=0.10.0=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py311h1ea47a8_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=py311h1ea47a8_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.15.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.3.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_1
  - jxrlib=1.1=hcfcfb64_3
  - kiwisolver=1.4.7=py311h3257749_0
  - krb5=1.21.3=hdf4eb48_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=hbcf6048_0
  - legacy-api-wrap=1.4.1=pyhd8ed1ab_0
  - lerc=4.0.0=h63175ca_0
  - libaec=1.1.3=h63175ca_0
  - libavif16=1.1.1=h4d049a7_2
  - libblas=3.9.0=29_h576b46c_mkl
  - libbrotlicommon=1.1.0=h2466b09_2
  - libbrotlidec=1.1.0=h2466b09_2
  - libbrotlienc=1.1.0=h2466b09_2
  - libcblas=3.9.0=29_h7ad3364_mkl
  - libclang13=19.1.7=default_ha5278ca_1
  - libcurl=8.12.1=h88aaa65_0
  - libdeflate=1.23=h9062f6e_0
  - libexpat=2.6.4=he0c23c2_0
  - libffi=3.4.6=h537db12_0
  - libgcc=14.2.0=h1383e82_1
  - libglib=2.82.2=h7025463_1
  - libgomp=14.2.0=h1383e82_1
  - libhwloc=2.11.2=default_ha69328c_1001
  - libhwy=1.1.0=h91493d7_0
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - libjxl=0.11.1=h456c5fc_0
  - liblapack=3.9.0=29_hacfb0e4_mkl
  - liblzma=5.6.4=h2466b09_0
  - liblzma-devel=5.6.4=h2466b09_0
  - libogg=1.3.5=h2466b09_0
  - libpng=1.6.46=had7236b_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.48.0=h67fdade_1
  - libssh2=1.11.1=he619c9f_0
  - libtiff=4.7.0=h797046b_3
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.5.0=h3b0e114_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.5=he286e8c_1
  - libxslt=1.1.39=h3df6e99_0
  - libzlib=1.3.1=h2466b09_2
  - libzopfli=1.0.3=h0e60522_0
  - llvmlite=0.44.0=py311h7deaa30_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.10.0=h2466b09_1
  - markupsafe=3.0.2=py311h5082efb_1
  - matplotlib=3.10.0=py311h1ea47a8_0
  - matplotlib-base=3.10.0=py311h8f1b1e4_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.1=pyhd8ed1ab_0
  - mkl=2024.2.2=h66d3029_15
  - munkres=1.0.7=py_1
  - natsort=8.4.0=pyh29332c3_1
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4=pyhd8ed1ab_0
  - notebook=7.3.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.61.0=py311h0673bce_1
  - numexpr=2.10.2=mkl_py311hd5da7cd_0
  - numpy=1.26.4=py311h0b4df5a_0
  - openjpeg=2.5.3=h4d64b90_0
  - openssl=3.4.1=ha4e3fda_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=1.5.3=py311hf63dbb6_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=h3d7b363_2
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py311h43e43bb_0
  - pip=25.0.1=pyh8b19718_0
  - pixman=0.44.2=had0cd8c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - ply=3.11=pyhd8ed1ab_3
  - prometheus_client=0.21.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.50=pyha770c72_0
  - prompt_toolkit=3.0.50=hd8ed1ab_0
  - psutil=6.1.1=py311he736701_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pyqt=5.15.9=py311h125bc19_5
  - pyqt5-sip=12.12.2=py311h12c1d0e_5
  - pyside6=6.8.2=py311h4238720_0
  - pysocks=1.7.1=pyh09c184e_7
  - pytables=3.10.2=py311ha92d589_0
  - python=3.11.3=h2628c8c_0_cpython
  - python-annoy=1.17.3=py311hda3d55a_2
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.11=5_cp311
  - pytz=2024.1=pyhd8ed1ab_0
  - pywavelets=1.8.0=py311h0a17f05_0
  - pywin32=307=py311hda3d55a_3
  - pywinpty=2.0.15=py311hda3d55a_0
  - pyyaml=6.0.2=py311h5082efb_2
  - pyzmq=26.2.1=py311h484c95c_0
  - qhull=2020.2=hc790b64_5
  - qt-main=5.15.15=h9151539_2
  - qt6-main=6.8.2=h1259614_0
  - rav1e=0.6.6=h975169c_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.22.3=py311h533ab2d_0
  - scanorama=1.7.4=pyhdfd78af_0
  - scanpy=1.10.4=pyhd8ed1ab_0
  - scikit-image=0.20.0=py311hf63dbb6_1
  - scikit-learn=1.2.2=py311h142b183_2
  - scipy=1.14.1=py311hf16d85f_2
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh5737063_1
  - session-info=1.0.0=pyhd8ed1ab_0
  - setuptools=75.8.0=pyhff2d567_0
  - setuptools-scm=8.1.0=pyhd8ed1ab_1
  - setuptools_scm=8.1.0=hd8ed1ab_1
  - sinfo=0.3.1=py_0
  - sip=6.7.12=py311h12c1d0e_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h500f7fa_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.4=py311h0a17f05_0
  - stdlib-list=0.11.0=pyhd8ed1ab_1
  - svt-av1=2.3.0=he0c23c2_0
  - tbb=2021.13.0=h62715c5_1
  - terminado=0.18.1=pyh5737063_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tifffile=2025.1.10=pyhd8ed1ab_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.4.2=py311he736701_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20241206=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025a=h78e105d_0
  - ucrt=10.0.22621.0=h57928b3_1
  - umap-learn=0.5.7=py311h1ea47a8_1
  - unicodedata2=16.0.0=py311he736701_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.3.0=pyhd8ed1ab_0
  - vc=14.3=h5fd82a7_24
  - vc14_runtime=14.42.34433=h6356254_24
  - vs2015_runtime=14.42.34433=hfef2bbc_24
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.13=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xz=5.6.4=h208afaa_0
  - xz-tools=5.6.4=h2466b09_0
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.5=ha9f60a1_7
  - zfp=1.0.1=he0c23c2_2
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib-ng=2.2.4=hbb528cf_0
  - zstandard=0.23.0=py311h53056dc_1
  - zstd=1.5.6=h0ea2cb4_0
  - pip:
      - bbknn==1.6.0
prefix: C:\Users\Miguel\.conda\envs\RNAseq
